### ISSUE TITLE
Translation problem of English version

### ISSUE THREAD

**Issue by bangjiehan** [bmeviauac01/datadriven#66]
In the end of this [section](https://bmeviauac01.github.io/datadriven/en/lecture-notes/transactions/#scheduling-enforced-with-locks), there is a note:

> When a deadlock happens, there is usually no other resolution to retry the operation later (e.g., automatically, or manually requested by the end-user).

It looks somehow strange and seems not a exact translation of original text.
Maybe it should be '..., there is usually no other solution than retrying the operation later ...' or '..., there is usually no other solution but to retry the operation later ...'
I am not a experienced English user and don't know Hungarian at all so I post this issue.

**Comment by tibitoth** [comment]
@bangjiehan Thank you! You are complately right. I've just fixed the translation
